version: 2
updates:
- package-ecosystem: gradle
  directory: "/components/micronaut/emissary/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - limpid-kzonix
  assignees:
  - limpid-kzonix
