kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: golang:1.12
    commands:
      - echo Running tests...
    when:
      event:
        - custom

  - name: build
    image: golang:1.12
    commands:
      - echo Building...

  - name: publish
    image: golang:1.12
    commands:
      - echo Publishing artifact

  - name: docker-hub
    image: golang:1.12
    environment:
      TEST_ENV: Test
    commands:
      - echo Docker Hub $TEST_ENV
when:
  event:
    - custom
---
kind: pipeline
type: ssh
name: ssh-connect

server:
  host:
    from_secret: SSH_HOST
  user:
    from_secret: SSH_LOGIN
  password:
    from_secret: SSH_PASS

steps:
  - name: command
    commands:
      - echo To be replaced with command for deployment
