kind: pipeline
type: docker
name: test

trigger:
  branch:
    - main
  event:
    - custom
steps:
  - name: test
    image: golang:1.15
    commands:
      - echo Running tests...
    when:
      event:
        - custom

  - name: build
    image: golang:1.15
    commands:
      - echo Building...
    when:
      event:
        - custom

  - name: publish
    image: golang:1.15
    commands:
      - echo Publishing artifact
    when:
      event:
        - custom
  - name: docker-hub
    image: golang:1.15
    environment:
      TEST_ENV: Test
    commands:
      - echo Docker Hub $TEST_ENV
    when:
      event:
        - custom
---
kind: pipeline
type: ssh
name: ssh-connect

trigger:
  branch:
    - main
  event:
    - custom

server:
  host:
    from_secret: SSH_HOST
  user:
    from_secret: SSH_LOGIN
  password:
    from_secret: SSH_PASS

steps:
  - name: command
    commands:
      - echo To be replaced with command for deployment
    when:
      event:
        - custom
