kind: pipeline
type: docker
name: Test

steps:
- name: Test
  image: golang:1.12
  commands:
  - echo Running tests...
  
- name: Build
  image: golang:1.12
  commands:
  - echo Building...

- name: Publishing
  image: golang:1.12
  commands:
  - echo Publishing artifact

- name: Docker Hub
  image: golang:1.12
  commands:
  - echo Docker Hub
---
kind: pipeline
type: ssh
name: SSH Connection to Master Deployment Server

server:
  host: 
    from_secret: SSH_HOST
  user: 
    from_secret: SSH_LOGIN
  password:
    from_secret: SSH_PASS

steps:
- name: greeting
  depends_on:
  - Docker Hub
  commands:
  - echo To be replaced with command for deployment
