kind: pipeline
type: docker
name: Test

steps:
- name: greeting
  image: golang:1.12
  commands:
  - echo Running tests...
---
kind: pipeline
type: docker
name: Publishing artifact

steps:
- name: greeting
  image: golang:1.12
  commands:
  - echo Publishing artifact
---
kind: pipeline
type: docker
name: Docker Hub

steps:
- name: greeting
  image: golang:1.12
  commands:
  - echo Docker Hub
---
kind: pipeline
type: ssh
name: SSH Connection to Master Deployment Server

server:
  host: 
    from_secret: SSH_HOST
  user: 
    from_secret: SSH_LOGIN
  password:
    from_secret: SSH_PASS

steps:
- name: greeting
  environment:
    PASS: 
      from_secret: SSH_PASS
  commands:
  - echo To be replaced with command for deployment
  - echo ${SSH_PASS} | sudo -S apt update
