kind: pipeline
type: docker
name: test

steps:
- name: test
  image: golang:1.12
  commands:
  - echo Running tests...
  
- name: build
  image: golang:1.12
  commands:
  - echo Building...

- name: publish
  image: golang:1.12
  commands:
  - echo Publishing artifact

- name: docker-hub
  image: golang:1.12
  commands:
  - echo Docker Hub
---
kind: pipeline
type: ssh
name: ssh-connect
depends_on:
- test
server:
  host: 
    from_secret: SSH_HOST
  user: 
    from_secret: SSH_LOGIN
  password:
    from_secret: SSH_PASS

steps:
- name: command
  commands:
  - echo To be replaced with command for deployment
