pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=continuous-integration/jenkins/branch
      - status-success=continuous-integration/jenkins/pr-head
      - status-success=continuous-integration/jenkins/pr-merge
      - "#review-requested=0"
      - label!=block-merge
      - label=dependencies
    actions:
      merge:
        merge:
          strict: true
          strict_method: rebase
          method: squash

  - name: Delete the merge-when-green label after merge
    conditions:
      - merged
      - label=block-merge
    actions:
      label:
        remove: [block-merge]
  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: 
