datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
micronaut:
  metrics:
    export:
      elastic:
        enabled: true
        step: PT1M
      influx:
        enabled: true
        step: PT1M
    enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
elasticsearch.httpHosts: '"http://localhost:9200,http://127.0.0.2:9200"'
jpa.default.properties.hibernate.hbm2ddl.auto: update
consul.client.registration.enabled: true
nats.addresses:
- nats://localhost:4222
