name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build with Gradle
      run: cd components/micronaut/emissary && gradle build
